//! Wire-format fixture tests for the JSON-RPC surface.
//!
//! Each fixture is generated by `tests/fixtures/gen` using upstream primitives
//! (op-service/signer types or go-ethereum's `rpc.Client` marshaling) so the
//! inputs are byte-for-byte what op-batcher puts on the wire. The Rust side
//! drives the production handler against those inputs and compares the result
//! to the expected output captured in the fixture.

use alloy::{
    consensus::TypedTransaction,
    eips::eip2718::Encodable2718,
    network::TxSigner,
    primitives::{hex, Address, Signature, B256},
    signers::{local::PrivateKeySigner, Signer as AlloySigner},
};
use espresso_kms_signer::{
    rpc::{SignerRpcServer, SignerServer},
    signer::Signer,
    tx_builder::TransactionArgs,
    Config,
};
use jsonrpsee::core::async_trait;
use std::{path::Path, sync::Arc};

const CHAIN_ID: u64 = 11155111;

fn fixture_path(name: &str) -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(format!("{name}.json"))
}

fn load<T: serde::de::DeserializeOwned>(path: &Path) -> T {
    let raw =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()))
}

// --- TestSigner: a PrivateKeySigner-backed Signer impl used to drive the
// production handler in tests without touching AWS KMS.
struct TestSigner(PrivateKeySigner);

#[async_trait]
impl Signer for TestSigner {
    fn address(&self) -> Address {
        TxSigner::address(&self.0)
    }
    async fn sign_transaction(
        &self,
        tx: &mut TypedTransaction,
    ) -> Result<Signature, alloy::signers::Error> {
        TxSigner::sign_transaction(&self.0, tx).await
    }
    async fn sign_hash(&self, hash: &B256) -> Result<Signature, alloy::signers::Error> {
        AlloySigner::sign_hash(&self.0, hash).await
    }
}

fn server_for(private_key: &str) -> (SignerServer<TestSigner>, Address) {
    let pk: PrivateKeySigner = private_key
        .parse()
        .unwrap_or_else(|e| panic!("bad private key: {e}"));
    let address = TxSigner::address(&pk);
    let signer = Arc::new(TestSigner(pk));
    let config = Arc::new(Config {
        kms_key_id: "fixture".into(),
        chain_id: CHAIN_ID,
        listen_addr: "127.0.0.1:0".parse().unwrap(),
        allowed_to: None,
        tls: None,
    });
    (SignerServer::new(signer, config), address)
}

// ---- eth_signTransaction fixtures -------------------------------------------------

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct TxFixture {
    description: String,
    private_key: String,
    input: TransactionArgs,
    expected_rlp: String,
}

async fn run_tx_fixture(path: &Path) {
    let fixture: TxFixture = load(path);

    let signer: PrivateKeySigner = fixture
        .private_key
        .parse()
        .unwrap_or_else(|e| panic!("{}: bad private key: {e}", fixture.description));

    let mut typed_tx: TypedTransaction = fixture
        .input
        .into_typed_transaction()
        .unwrap_or_else(|e| panic!("{}: into_typed_transaction: {e}", fixture.description));

    let sig = signer
        .sign_transaction(&mut typed_tx)
        .await
        .unwrap_or_else(|e| panic!("{}: sign: {e}", fixture.description));

    let got = format!(
        "0x{}",
        hex::encode(typed_tx.into_envelope(sig).encoded_2718())
    );
    assert_eq!(
        got, fixture.expected_rlp,
        "{}: RLP mismatch",
        fixture.description
    );
}

// ---- espresso_signBatch fixtures ---------------------------------------------------
//
// The fixture's `params` field stores the JSON-RPC params array byte-for-byte
// as produced by go-ethereum's `rpc.Client` for the batcher's signBatch call —
// i.e. `[address, base64(batchRLP)]`, where the RLP encodes a real
// espresso-streamers `EspressoBatch`. The test deserialises that into the same
// (Address, String) shape our handler expects and calls the production handler
// directly, exercising the decode + shape check + hash + sign + format path.
// The expected signature is go-ethereum's `crypto.Sign` over keccak256 of the
// payload bytes — the digest `ToEspressoTransaction` computes in production.

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct SignFixture {
    description: String,
    private_key: String,
    params: (Address, String),
    expected_sig: String,
}

async fn run_sign_fixture(path: &Path) {
    let fixture: SignFixture = load(path);
    let (srv, signer_address) = server_for(&fixture.private_key);
    assert_eq!(
        signer_address, fixture.params.0,
        "{}: signer address mismatch",
        fixture.description
    );

    let got = srv
        .espresso_sign_batch(fixture.params.0, fixture.params.1.clone())
        .await
        .unwrap_or_else(|e| panic!("{}: espresso_signBatch: {e:?}", fixture.description));

    assert_eq!(
        got, fixture.expected_sig,
        "{}: signature mismatch",
        fixture.description
    );
}

// ---- espresso_signBatch reject fixtures --------------------------------------------
//
// REQ-SIDECAR-S-003 AC-1: transaction signing-preimages, non-RLP messages, and
// structural near-misses must all be refused before any KMS call. Payloads are
// generated by the Go side (real geth encodings where applicable).

#[derive(serde::Deserialize)]
struct RejectFixture {
    description: String,
    payload: String, // base64, as on the wire
}

#[tokio::test]
async fn espresso_sign_batch_rejects() {
    let fixtures: Vec<RejectFixture> = load(&fixture_path("espresso_sign_batch_rejects"));
    assert!(!fixtures.is_empty(), "rejects fixture file is empty");
    let (srv, signer_address) = server_for(TEST_KEY);

    for f in fixtures {
        let err = srv
            .espresso_sign_batch(signer_address, f.payload)
            .await
            .expect_err(&format!("{}: must be rejected", f.description));
        // -32602 can only come from the validation path; a signing failure
        // maps to -32000. The code alone proves no KMS call was attempted.
        assert_eq!(err.code(), -32602, "{}: wrong error code", f.description);
    }
}

const TEST_KEY: &str = "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";

macro_rules! tx_fixture_test {
    ($name:ident) => {
        #[tokio::test]
        async fn $name() {
            run_tx_fixture(&fixture_path(stringify!($name))).await;
        }
    };
}

macro_rules! sign_fixture_test {
    ($name:ident) => {
        #[tokio::test]
        async fn $name() {
            run_sign_fixture(&fixture_path(stringify!($name))).await;
        }
    };
}

tx_fixture_test!(eip1559_basic);
tx_fixture_test!(eip1559_with_data);
tx_fixture_test!(eip4844_basic);
sign_fixture_test!(espresso_sign_batch_basic);
